### ISSUE TITLE
Add proper logging

### ISSUE THREAD

**Issue by quidome** [simisimis/dalia#6]
The code contains print statements that could be moved to (verbose) logging.

Let's see if we can add proper logging with some verbosity levels.

**Comment by gmarouli** [comment]
I will checkout if we can use this: https://docs.rs/log/latest/log/

**Comment by simisimis** [comment]
in another project I am working with Koen, coincidentally he suggested to use log for library things and https://docs.rs/pretty_env_logger/0.4.0/pretty_env_logger/
for binary

**Comment by simisimis** [comment]
in another project I am working with Koen, coincidentally he suggested to use log for library things and https://docs.rs/pretty_env_logger/0.4.0/pretty_env_logger/
for binary

**Comment by gmarouli** [comment]
@simisimis I will take a look, if you know (or you could find out) why he had that preference, please share, I am really curious to know.
